import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Hero from "@/components/hero";
import Contact from "@/components/contact";
import Project from "@/components/project";
import About from "@/components/about";
import Skill from "@/components/skill";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Hero />
        <About />
        <Skill/>
      <Project />
        <Contact />
        <Footer />
        
        {children}</body>
    </html>
  );
}
